API_HOST_URL: 'https://lms-dev-ksu.raccoongang.com'
ENVIRONMENT_DISPLAY_NAME: 'KSU'
FEEDBACK_EMAIL_ADDRESS: 'Tp-mobile@ksu.edu.sa'

DEBUG: true
MY_VIDEOS_ENABLED: true
COURSE_VIDEOS_ENABLED: true
ANNOUNCEMENTS_ENABLED: true

DISCOVERY: {
  COURSE: {
    TYPE: 'native'
  }
}

COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }

COURSE_SHARING_ENABLED: true
DOWNLOAD_TO_SD_CARD_ENABLED: true
COURSE_DATES_ENABLED: true
TAB_LAYOUTS_ENABLED: true
OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true
DISCUSSIONS_ENABLED: true
NEW_LOGISTRATION_ENABLED: false
CERTIFICATES_ENABLED: true
REGISTRATION_ENABLED: true
APP_REVIEWS_ENABLED: true
WHATS_NEW_ENABLED: false
USING_VIDEO_PIPELINE: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
